# Generated by Django 2.0.7 on 2018-07-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='project_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.CharField(max_length=3),
        ),
    ]
